name: Run Aggregator

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Clone aggregator
        run: git clone https://github.com/wzdnzd/aggregator.git

      - name: Install dependencies
        run: |
          cd aggregator
          pip install -r requirements.txt

      - name: Run collect script
        run: |
          cd aggregator
          python -u subscribe/collect.py -s

      - name: Commit and push aggregator data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f aggregator/data
          git commit -m "Update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
